export const dadosEstados = {
    'AC': { nome: 'Acre', regiao: 'Norte', capital: 'Rio Branco', populacao: 906876 },
    'AL': { nome: 'Alagoas', regiao: 'Nordeste', capital: 'Maceió', populacao: 3365351 },
    'AP': { nome: 'Amapá', regiao: 'Norte', capital: 'Macapá', populacao: 877613 },
    'AM': { nome: 'Amazonas', regiao: 'Norte', capital: 'Manaus', populacao: 4308057 },
    'BA': { nome: 'Bahia', regiao: 'Nordeste', capital: 'Salvador', populacao: 14985284 },
    'CE': { nome: 'Ceará', regiao: 'Nordeste', capital: 'Fortaleza', populacao: 9240580 },
    'DF': { nome: 'Distrito Federal', regiao: 'Centro-Oeste', capital: 'Brasília', populacao: 3094325 },
    'ES': { nome: 'Espírito Santo', regiao: 'Sudeste', capital: 'Vitória', populacao: 4108508 },
    'GO': { nome: 'Goiás', regiao: 'Centro-Oeste', capital: 'Goiânia', populacao: 7206589 },
    'MA': { nome: 'Maranhão', regiao: 'Nordeste', capital: 'São Luís', populacao: 7153262 },
    'MT': { nome: 'Mato Grosso', regiao: 'Centro-Oeste', capital: 'Cuiabá', populacao: 3567234 },
    'MS': { nome: 'Mato Grosso do Sul', regiao: 'Centro-Oeste', capital: 'Campo Grande', populacao: 2839188 },
    'MG': { nome: 'Minas Gerais', regiao: 'Sudeste', capital: 'Belo Horizonte', populacao: 21168791 },
    'PA': { nome: 'Pará', regiao: 'Norte', capital: 'Belém', populacao: 8777124 },
    'PB': { nome: 'Paraíba', regiao: 'Nordeste', capital: 'João Pessoa', populacao: 4059905 },
    'PR': { nome: 'Paraná', regiao: 'Sul', capital: 'Curitiba', populacao: 11597484 },
    'PE': { nome: 'Pernambuco', regiao: 'Nordeste', capital: 'Recife', populacao: 9674793 },
    'PI': { nome: 'Piauí', regiao: 'Nordeste', capital: 'Teresina', populacao: 3289290 },
    'RJ': { nome: 'Rio de Janeiro', regiao: 'Sudeste', capital: 'Rio de Janeiro', populacao: 17264943 },
    'RN': { nome: 'Rio Grande do Norte', regiao: 'Nordeste', capital: 'Natal', populacao: 3560903 },
    'RS': { nome: 'Rio Grande do Sul', regiao: 'Sul', capital: 'Porto Alegre', populacao: 11422973 },
    'RO': { nome: 'Rondônia', regiao: 'Norte', capital: 'Porto Velho', populacao: 1815278 },
    'RR': { nome: 'Roraima', regiao: 'Norte', capital: 'Boa Vista', populacao: 652713 },
    'SC': { nome: 'Santa Catarina', regiao: 'Sul', capital: 'Florianópolis', populacao: 7338473 },
    'SP': { nome: 'São Paulo', regiao: 'Sudeste', capital: 'São Paulo', populacao: 45919049 },
    'SE': { nome: 'Sergipe', regiao: 'Nordeste', capital: 'Aracaju', populacao: 2338474 },
    'TO': { nome: 'Tocantins', regiao: 'Norte', capital: 'Palmas', populacao: 1607363 }
};